### ISSUE TITLE
Ошибка!

### ISSUE THREAD

**Issue by ValenokPC** [mr-Evgen/dle-billing-module#2]
https://github.com/mr-Evgen/dle-billing-module/blob/43b285272d2fa62bf291a6af31ca8ed22aaaf4dd/engine/modules/billing/controllers/user.pay.php#L35

Если число умножить на ноль то будет ноль! Нужно заменить на сложение!

**Comment by mr-Evgen** [comment]
$_Payment['convert'] - коэф. конвертирования
